//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootTouch {
    
    private rootTouchZone[] zoneField;
    
    private string keyField;
    
    private string picField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("zone", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootTouchZone[] zone {
        get {
            return this.zoneField;
        }
        set {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pic {
        get {
            return this.picField;
        }
        set {
            this.picField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootTouchZone {
    
    private string y1Field;
    
    private string y2Field;
    
    private string x1Field;
    
    private string x2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y1 {
        get {
            return this.y1Field;
        }
        set {
            this.y1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y2 {
        get {
            return this.y2Field;
        }
        set {
            this.y2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x1 {
        get {
            return this.x1Field;
        }
        set {
            this.x1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x2 {
        get {
            return this.x2Field;
        }
        set {
            this.x2Field = value;
        }
    }
}
